### ISSUE TITLE
SdkError: Incorrect webhook request token

### ISSUE THREAD

**Issue by TimPchelintsev** [jfkz/tinkoff-payment-sdk#5]
Успешно принимал несколько месяцев платежи на самописном сайте, рабочий терминал в Тинькофф Кассе включен,
ключи не менялись, на днях после успешной оплаты в функции обработки webhook без изменения кода там начала вылетать ошибка:

```
SdkError: Incorrect webhook request token
    at WebhookHandler.handleWebhookRequest (/var/task/app/node_modules/@jfkz/tinkoff-payment-sdk/dist/webhook-handler/webhook-handler.js:31:19)
    at tinkoffWebhook (/var/task/app/.next/server/pages/api/webhooks/tinkoff.js:230:47)
    at /var/task/app/node_modules/next/dist/server/api-utils/node.js:440:16
    at /var/task/app/node_modules/next/dist/server/lib/trace/tracer.js:113:36
    at NoopContextManager.with (/var/task/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/var/task/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/var/task/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/var/task/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /var/task/app/node_modules/next/dist/server/lib/trace/tracer.js:102:107
    at NoopContextManager.with (/var/task/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/var/task/app/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NextTracerImpl.trace (/var/task/app/node_modules/next/dist/server/lib/trace/tracer.js:102:32)
    at apiResolver (/var/task/app/node_modules/next/dist/server/api-utils/node.js:438:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (/var/task/app/node_modules/next/dist/server/next-server.js:668:9)
    at async Object.fn (/var/task/app/node_modules/next/dist/server/next-server.js:1132:35) {
  payload: {}
}
Error: Runtime exited without providing a reason
Runtime.ExitError
```

Посмотрел по коду библиотеки, в функции handleWebhookRequest:
```js
// Validating request token
// -----

const checkToken = generateSignature({
  payload,
  password,
});

if (payload?.Token !== checkToken) {
  throw new SdkError({
    payload,
    message: 'Incorrect webhook request token',
  });
}
```
Выходит, если в коде библиотеки и на моей стороне ничего не менялось, что-то изменилось на стороне Тинькофф?

**Comment by TimPchelintsev** [comment]
Протестировал платежи локально на тестовом терминале, работает как и прежде.
Выходит, перестало работать только на продакшн(vercel), там ключи как стояли так и стоят.
Нашел документацию Тинькофф, https://www.tinkoff.ru/kassa/dev/payments/#tag/Notifikacii-Merchanta-ob-operaciyah/Notifikacii-po-HTTP(s)/Proverka-tokenov

Сверил с реализацией в коде библиотеки, изменений тоже не видно.
Написал в чат Тинькофф Бизнес, посмотрим что они скажут.

**Comment by jfkz** [comment]
@TimPchelintsev 

Попробуй зафиксировать на версии 1.3.2, например. Я принял коммит исключительно по СДК: https://github.com/jfkz/tinkoff-payment-sdk/commit/fa69766c32e38bbff8c861091452cc75ee6807b4, но у меня не было возможности его протестировать на реальном примере. У Тинькова нормальная практика расхождения реального АПИ и задокументированного, поэтому вполне может быть баг в именовании полей.

Либо действительно действовать по ответу от саппорта.
